### ISSUE TITLE
Consider Adding Edit Support

### ISSUE THREAD

**Issue by jlukic** [necarlson97/codex-ai-sublime#1]
Thanks for creating this plugin, its a nice utility for getting at the APIs. 

OpenAI has now launched a new engine specifically for editing/rewriting code. It has a lot of benefits over code generation from scratch because you can give it a lot more prompts around how you like to write/structure your code.

Announce blog post:
https://openai.com/blog/gpt-3-edit-insert/

Docs:
https://beta.openai.com/docs/guides/code/editing-code

You can hit the edit endpoint 
```
https://api.openai.com/v1/engines/{engine_id}/edits
```

Using  `code-davinci-edit-001`  as the `engine_id`

You most likely would want to add an additional user prompt to allow the user to specify the `instruction`.

**Comment by jlukic** [comment]
For fun I had the open ai insert endpoint try to write this function itself
```python
    def get_edit_response(self, prompt,key):/*
        """
        * Takes the users selected value as "prompt" and pass into the API as field "input"
        * Asks the user to specify an "instructions" parameter to pass into the API endpoint
        * Queries open AI edit endpoint "https://api.openai.com/v1/engines/{engine_id}/edits" using engine id "text-davinci-edit-001"
        * For more information on the edit endpoint <https://beta.openai.com/docs/api-reference/edits>
        * Returns the response from Open AI
        */
        """
       # settings = sublime.load_settings('codex-ai.sublime-settings')
        instructions = sublime.active_window().show_input_panel("Instructions","","",None,None)
        response = requests.post(
            'https://api.openai.com/v1/engines/text-davinci-edit-001/edits',
            headers={
                'Authorization': "Bearer " + key,
                'Content-Type': 'application/json',
            },
            data=json.dumps({
                'input': prompt,
                'instructions': instructions,
            }),
            verify='/etc/ssl/certs'
        )

        #respone_dict = response.json()

        if response.get('Error', None):
            raise ValueError(respone_dict['Error'])
        else:
            choice = response.get('choices', [{}])[0]
            ai_text = choice.get('text', response.text)
        return ai_text
```

**Comment by necarlson97** [comment]
Thanks for the suggestion! Makes me very happy to see another soul has used this plugin besides myself.

The `edits` endpoint looks perfect for this project, hopefully I'll get some time this week to look into it.

Love being able to use Codex plugin to write Codex plugin - one big meta-joke, somehow deeply satisfying.

**Comment by necarlson97** [comment]
Alright! Added the new 'edits' command to release [v1.3.0](https://github.com/necarlson97/codex-ai-sublime/releases/tag/v1.3.0) - Codex can still be a bit unwieldy, as the 'edits' endpoint is still in beta, but it is very fun to use.

Check the current readme with updated git and use info.
Thank you kindly for the suggestion! Let me know what you think
