### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by 7k50** [necarlson97/codex-ai-sublime#3]
The documentation on how to install is rather sparse, from what I can see.

The package is not available in Sublime Text's Command Palette > `Package Control: Install Package` as far I can tell?

I tried `Preferences > Browse Packages` to open the local packages folder, then in Terminal `git clone https://github.com/necarlson97/codex-ai-sublime`.

If I try to edit `Preferences > Package Settings > CodexAI > Settings` I get the error:

> The settings file "res://Packages/CodexAI/codex-ai.sublime-settings" could not be opened

I opened edited the `codex-ai.sublime-settings` manually via MacOS Finder and inserted my OpenAI Codex API key.
`"open_ai_key": "MY_KEY",`

After restarting Sublime Text, writing some simple Python code, and with the Command Palette I select `Codex AI: Generate AI text from highlighted prompt` I see that `Codex is thinking` indefinitely.

Was this process correct?

**Comment by necarlson97** [comment]
It sounds like you may be on a Mac - this package is currently only available for Linux. I would love to add mac (and windows) support in the future - if you are able to get it working, I would happily merge a PR.

I cannot say how well downloading and installing from this github repo on a mac will work as I have not tried it - mac and linux are both unix systems, but the python is not likely to work cross-platform without some tweaking. If you like, I encourage you to try some of this yourself: use `view > show console` to get more info from sublime about what the python error may be. I am happy to provide more resources about how to code packages for sublime-text (though I am far from an expert).

I wish I could help you more, but unfortunately, I don't have access to a mac. As I said, if you are able to solve this problem in code, I can happily review your fix (best I am able) and see if we can publish to get other mac users access.

Thoughts?

**Comment by 7k50** [comment]
@necarlson97 Thanks very much for clarifying. I see that the Package Control page only says Linux.

Thank you for the assistance. I will get back to you if I find anything useful.
